### ISSUE TITLE
HM for the gunner

### ISSUE THREAD

**Issue by Patricktheorge** [Midoriykawa/Bernkastel-crack-berserk#1]

**Comment by Midoriykawa** [comment]
y

**Comment by Patricktheorge** [comment]
planing to buy xd

**Comment by Midoriykawa** [comment]
add me discord

**Comment by Tera-Scripts** [comment]
You are sad. people can see u edit my comments :)

Stop scamming people ty.

**Comment by Tera-Scripts** [comment]
You are sad. people can see u edit my comments :)

Stop scamming people ty.
