### ISSUE TITLE
.

### ISSUE THREAD

**Issue by dnndii132** [Midoriykawa/Bernkastel-crack-berserk#3]
do not use his services 100% scamm

**Comment by Midoriykawa** [comment]
rofl:D l2p kids
![image](https://user-images.githubusercontent.com/25081063/97808290-a5f78180-1c98-11eb-9f74-cbf713c9a9a2.png)

**Comment by Tera-Scripts** [comment]
You are sad. people can see u edit my comments :)

Stop scamming people ty.

**Comment by Tera-Scripts** [comment]
You are sad. people can see u edit my comments :)

Stop scamming people ty.
